a = input('Digite algo: ')
print('O tipo primitivo é', type(a))
print('Tem apenas espaços?', a.isspace())
print('É númerico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está em maiuscula?', a.isupper())
print('Está em minuscula?', a.islower())
print('Está centralizada?', a.istitle())